message(STATUS "Loading tests target...")

# ------------------------------------------------------------------------------ #
#                              Load sources                                      #
# ------------------------------------------------------------------------------ #

file(GLOB TEST_SOURCES
        "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp"
)

# ------------------------------------------------------------------------------ #
#                               Define exec                                      #
# ------------------------------------------------------------------------------ #

add_executable(${TEST} ${TEST_SOURCES})

# ------------------------------------------------------------------------------ #
#                                   Link                                         #
# ------------------------------------------------------------------------------ #

target_link_libraries(${TEST} PRIVATE
        ${CPU_LIB}
        ${CUDA_LIB}
        GTest::gtest_main
)

include(GoogleTest)
gtest_discover_tests(${TEST})